string = "The quick brown fox jumped over the lazy dog. 1 2 3 4 5"
mydict = {71: 62}
print(string)
print("All lowercase")
print(string.casefold())
print("How many times e occurs in string")
print(string.count("e"))
print("Does the string end with 4?")
print(string.endswith("4"))
print("Position of string \"quick\"")
print(string.find("quick"))
print("Are all characters in string alphanumeric?")
print(string.isalpha())
print("Are all words in the string decimal?")
print(string.isdecimal())
print("Is the string a valid identifier?")
print(string.isidentifier())
print("Are all words numeric?")
print(string.isdecimal())
print("Are all characters spaces?")
print(string.isspace())
print("Are all characters uppercase?")
print(string.isupper())
print("Left justified string followed by hello")
print(string.ljust(30), "hello")
print("stripping characters from left side")
print(string.lstrip("T"))
print("Splitting string into three parts with center at fox")
print(string.partition("fox"))
print("Find the last occurence of character g")
print(string.rfind("g"))
print("Splitting string at spaces")
print(string.split(" "))
print("Check if string starts with The")
print(string.startswith("The", 0, 2))
print("Swap all cases of letters")
print(string.swapcase())
print("Switch all instances of q to b")
print(string.translate(mydict))
print("Adds 0s to beginning of string until string is 80 characters long")
print(string.zfill(80))